version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: garden_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: garden_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  rest_api:
    build: ./rest_api
    container_name: garden_rest_api
    ports:
      - "8000:8000"
    volumes:
      - ./rest_api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto

  mqtt_worker:
    build: ./rest_api
    container_name: garden_mqtt_worker
    volumes:
      - ./rest_api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python manage.py mqtt
    depends_on:
      - mosquitto
      - redis

  celery_worker:
    build: ./rest_api
    container_name: garden_celery_worker
    volumes:
      - ./rest_api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="." -- sh -c "celery -A garden_api worker -l info"
    depends_on:
      - redis
      - rest_api

  celery_beat:
    build: ./rest_api
    container_name: garden_celery_beat
    volumes:
      - ./rest_api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="." -- sh -c "celery -A garden_api beat -l info"
    depends_on:
      - redis
      - rest_api
