# Generated by Django 4.1.13 on 2026-02-05 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('idChannel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machineId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(default='', max_length=100, unique=True)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idData', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('date_of_capture', models.DateTimeField(blank=True, null=True)),
                ('dataId', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.FloatField()),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('serial_machine', models.CharField(max_length=100)),
                ('channelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.channel')),
                ('machineId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
