# Generated by Django 4.1.13 on 2026-02-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('idPermission', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoints', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='core.permission')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('idUserRole', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationChannel',
            fields=[
                ('idConfigurationChannel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.channel')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
            options={
                'verbose_name_plural': 'Configuration Channels',
                'unique_together': {('machine', 'type')},
            },
        ),
    ]
