# Generated by Django 4.1.13 on 2026-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_role_alter_machine_serial_userrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='channels',
            field=models.JSONField(default=list),
        ),
    ]
