# Generated by Django 4.1.13 on 2026-02-16 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_permission_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='machines',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('idBusiness', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'unique_together': {('user', 'machine')},
            },
        ),
    ]
