# Generated by Django 4.1.13 on 2026-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
